import test from 'node:test';import assert from 'node:assert/strict';import worker from '../src/backend.mjs';import {environment} from './harness.mjs';
const origin='https://imprint.test';
async function call(env,path,method='GET',value,headers={}){const h={...headers};if(method!=='GET'){h.origin=origin;h['content-type']='application/json'}return worker.fetch(new Request(origin+path,{method,headers:h,body:value===undefined?undefined:JSON.stringify(value)}),env,{})}
async function signup(env,email){const r=await call(env,'/api/auth/register','POST',{email,name:'Khách thử',password:'Testing-Strong-2026'});assert.equal(r.status,201);return{cookie:r.headers.get('set-cookie').split(';')[0],user:(await r.json()).user}}
async function upload(env,cookie){const bytes=new Uint8Array([137,80,78,71]);const r=await worker.fetch(new Request(origin+'/api/upload',{method:'POST',headers:{origin,cookie,'content-type':'image/png','content-length':'4'},body:bytes}),env,{});assert.equal(r.status,201);return r.json()}
const shipping={fullName:'Khách thử',phone:'0912345678',city:'Hà Nội',ward:'Cầu Giấy',address:'Số 123 đường ABC'};
test('public catalogue, auth persistence and authorization',async()=>{const env=environment();const boot=await(await call(env,'/api/bootstrap')).json();assert.equal(boot.products.length,9);const {cookie,user}=await signup(env,'first@example.test');assert(!('password_hash'in(await(await call(env,'/api/bootstrap','GET',undefined,{cookie})).json()).user));assert.equal((await call(env,'/api/admin/settings/campaign','PUT',{value:'hack',revision:1},{cookie})).status,403);assert.equal((await call(env,'/api/admin/settings/campaign','PUT',{value:'hack',revision:1})).status,403);const asset=await upload(env,cookie);const b=await signup(env,'second@example.test');assert.equal((await call(env,asset.url,'GET',undefined,{cookie:b.cookie})).status,403);assert.equal((await call(env,asset.url,'GET',undefined,{cookie})).status,200);await call(env,'/api/auth/logout','POST',{}, {cookie});assert.equal((await(await call(env,'/api/bootstrap','GET',undefined,{cookie})).json()).user,null);const login=await call(env,'/api/auth/login','POST',{email:'first@example.test',password:'Testing-Strong-2026'});assert.equal(login.status,200);assert.equal((await login.json()).user.id,user.id);env.db.close()});
test('server prices, idempotency, stock rollback and private designs',async()=>{const env=environment(),{cookie,user}=await signup(env,'buyer@example.test'),boot=await(await call(env,'/api/bootstrap')).json(),p=boot.products.find(p=>p.id==='heavy'),asset=await upload(env,cookie);const item={id:'item-1',product:p,size:'M',color:'Đen',model:'m',qty:1,preview:asset.url,unit:1};let r=await call(env,'/api/cart','PUT',{items:[item],revision:0},{cookie});assert.equal(r.status,200);let c=await r.json();assert.equal(c.items[0].unit,p.price);r=await call(env,'/api/orders','POST',{cartRevision:c.revision,requestKey:'test-order-123',shipping,coupon:'CHAO10',total:1},{cookie});assert.equal(r.status,201);const order=await r.json();assert.equal(order.total,p.price+30000-Math.round(p.price*.1));const retry=await(await call(env,'/api/orders','POST',{cartRevision:c.revision,requestKey:'test-order-123',shipping},{cookie})).json();assert.equal(retry.id,order.id);assert.equal(env.db.prepare('SELECT stock FROM products WHERE id=?').get(p.id).stock,p.stock-1);const other=await signup(env,'other@example.test');assert.equal((await(await call(env,'/api/bootstrap','GET',undefined,{cookie:other.cookie})).json()).orders.length,0);
const d={id:'design-123',productId:p.id,layers:[{type:'image',asset:asset.id}]};r=await call(env,'/api/designs','POST',{id:d.id,design:d},{cookie});assert.equal(r.status,200);assert.equal((await call(env,'/api/designs','POST',{id:d.id,design:d},{cookie:other.cookie})).status,403);let pers=await(await call(env,'/api/bootstrap','GET',undefined,{cookie})).json();assert.equal(pers.designs.length,1);
r=await call(env,'/api/cart','PUT',{items:[{...item,qty:p.stock}],revision:2},{cookie});assert.equal(r.status,200);r=await call(env,'/api/orders','POST',{cartRevision:3,requestKey:'test-no-stock-123',shipping},{cookie});assert.equal(r.status,409);assert.equal(env.db.prepare('SELECT COUNT(*) AS n FROM orders').get().n,1);assert.equal(env.db.prepare('SELECT stock FROM products WHERE id=?').get(p.id).stock,p.stock-1);env.db.close()});
test('admin updates persist; customer role spoof and stale revisions rejected',async()=>{const env=environment();await call(env,'/api/bootstrap');const owner={'oai-authenticated-user-email':'owner@test.local'};let r=await call(env,'/api/admin/settings/campaign','PUT',{value:'Nội dung được lưu chung',revision:1},owner);assert.equal(r.status,200);assert.equal((await(await call(env,'/api/bootstrap')).json()).campaign,'Nội dung được lưu chung');assert.equal((await call(env,'/api/admin/settings/campaign','PUT',{value:'old',revision:1},owner)).status,409);const customer=await signup(env,'normal@example.test');assert.equal((await call(env,'/api/admin/settings/campaign','PUT',{value:'hack',revision:2,role:'admin'},{cookie:customer.cookie})).status,403);const bad=new Request(origin+'/api/auth/logout',{method:'POST',headers:{origin:'https://evil.test','content-type':'application/json'},body:'{}'});assert.equal((await worker.fetch(bad,env,{})).status,403);env.db.close()});
