import {build} from 'esbuild';import fs from 'node:fs';import crypto from 'node:crypto';import path from 'node:path';
const base=fs.readFileSync('src/index.html','utf8'),assets={};
function extract(data){const m=data.match(/^data:([^;]+);base64,([\w+/=]+)$/);if(!m)return data;const ext={'image/png':'png','image/webp':'webp','image/jpeg':'jpg','font/woff2':'woff2','font/woff':'woff','video/mp4':'mp4'}[m[1]]||'bin',name='/static/'+crypto.createHash('sha256').update(data).digest('hex')+'.'+ext;assets[name]={type:m[1],base64:m[2]};return name}
let html=base.replace(/data:[\w/+.-]+;base64,[\w+/=]+/g,extract);
const seed=JSON.parse(fs.readFileSync('src/seed.json','utf8'));for(const p of seed.products)p.img=extract(p.img);for(const c of seed.collections)c.src=extract(c.src);
html=html.replace('init().catch(e=>',fs.readFileSync('src/client-api.js','utf8')+'\ninit().catch(e=>');html=html.replace(/Không mở được bộ nhớ trình duyệt\./g,'Không kết nối được ImPrint.').replace('Hãy mở file bằng Chrome hoặc Edge, cho phép lưu dữ liệu và không dùng chế độ chặn lưu trữ.','Kiểm tra kết nối mạng, tải lại trang hoặc thử lại sau. Bản nháp trên thiết bị vẫn được giữ.');
fs.rmSync('dist',{recursive:true,force:true});fs.mkdirSync('dist/server',{recursive:true});fs.writeFileSync('dist/server/generated.mjs','export const html='+JSON.stringify(html)+';\nexport const builtAssets='+JSON.stringify(assets)+';\nexport const seedCatalog='+JSON.stringify(seed)+';\n');fs.copyFileSync('src/backend.mjs','dist/server/entry.mjs');await build({entryPoints:['dist/server/entry.mjs'],outfile:'dist/server/index.js',bundle:true,format:'esm',platform:'browser',target:'es2022'});fs.rmSync('dist/server/entry.mjs');fs.rmSync('dist/server/generated.mjs');if(fs.existsSync('.openai/hosting.json')){fs.mkdirSync('dist/.openai',{recursive:true});fs.copyFileSync('.openai/hosting.json','dist/.openai/hosting.json');}
fs.writeFileSync('src/generated.mjs','export const html="test";export const builtAssets={};export const seedCatalog='+JSON.stringify(seed)+';\n');
console.log(JSON.stringify({htmlBytes:html.length,assets:Object.keys(assets).length,products:seed.products.length}));
