// Server-only sales reporting and audited order outcomes. All calls require admin.
const DAY=86400000;
const fail=(status,message)=>{const e=new Error(message);e.status=status;throw e};
const sql=(db,q,...args)=>db.prepare(q).bind(...args);
const rows=async(db,q,...args)=>(await sql(db,q,...args).all()).results;
const row=(db,q,...args)=>sql(db,q,...args).first();
const response=value=>new Response(JSON.stringify(value),{headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}});
const clean=(v,n=500)=>typeof v==='string'?v.trim().slice(0,n):'';
function dayValue(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(s||''))fail(400,'Ngày phải có dạng YYYY-MM-DD.');const n=Date.parse(s+'T00:00:00+07:00');if(!Number.isFinite(n)||new Date(n+7*3600000).toISOString().slice(0,10)!==s)fail(400,'Ngày không tồn tại.');return n}
function period(params,defaultRange=true){const today=new Date(Date.now()+7*3600000).toISOString().slice(0,10);const endText=params.get('to')||(defaultRange?today:'2100-12-31');const startText=params.get('from')||(defaultRange?new Date(dayValue(endText)-29*DAY+7*3600000).toISOString().slice(0,10):'1970-01-01');const start=dayValue(startText),end=dayValue(endText)+DAY;if(start>=end)fail(400,'Ngày bắt đầu phải trước hoặc bằng ngày kết thúc.');if(defaultRange&&end-start>366*DAY)fail(400,'Chọn tối đa 366 ngày mỗi lần.');return{from:startText,to:endText,start,end}}
const NET="MAX(0,COALESCE(json_extract(o.body,'$.sub'),0)-COALESCE(json_extract(o.body,'$.discount'),0))";
export const ORDER_TRANSITIONS={0:[1,2,3,4,5,6],1:[2,3,4,5,6],2:[3,4,5,6],3:[4,5,6],4:[5,7],5:[7],6:[],7:[5,8],8:[]};
export async function updateSalesOrder(db,id,p,admin){const found=await row(db,'SELECT * FROM orders WHERE id=?',id);if(!found)fail(404,'Không tìm thấy đơn hàng.');const o=JSON.parse(found.body),previous=o.status,revision=o.revision||0;if(p.expectedRevision!==revision)fail(409,'Đơn đã được cập nhật ở nơi khác. Tải lại danh sách rồi thử lại.');if(!Number.isInteger(p.status)||p.status<0||p.status>8)fail(400,'Trạng thái đơn chưa hợp lệ.');const changed=p.status!==previous;if(changed&&!ORDER_TRANSITIONS[previous]?.includes(p.status))fail(400,'Không thể chuyển đơn sang trạng thái này.');const reason=clean(p.reason,1000);if(changed&&([6,7,8].includes(p.status)||previous===7)&&reason.length<3)fail(400,'Nhập lý do ít nhất 3 ký tự cho việc hủy/hoàn hoặc từ chối hoàn.');if(p.restock!==undefined&&typeof p.restock!=='boolean')fail(400,'Lựa chọn nhập lại kho chưa hợp lệ.');if(p.restock&&(!changed||![6,8].includes(p.status)||o.stockRestored))fail(400,'Chỉ nhập lại kho một lần khi xác nhận hủy hoặc đã hoàn hàng.');const now=new Date().toISOString(),tracking=typeof p.tracking==='string'?clean(p.tracking,100):o.tracking||'';if(!changed&&tracking===o.tracking)return o;const actionId=crypto.randomUUID();o.revision=revision+1;o.updatedAt=now;o.lastActionId=actionId;o.history=Array.isArray(o.history)?o.history:[];o.history.push({status:p.status,from:previous,at:now,actor:admin.email||admin.id,reason:changed?reason:'Cập nhật vận đơn',kind:changed?'status':'tracking',restocked:!!p.restock});o.status=p.status;o.tracking=tracking;if(changed&&p.status===6){o.cancelReason=reason;o.cancelledAt=now}if(changed&&p.status===7){o.returnReason=reason;o.returnRequestedAt=now}if(changed&&p.status===8){o.returnReason=reason;o.returnedAt=now}if(p.restock){o.stockRestored=true;o.stockRestoredAt=now}const needs={};if(p.restock)for(const item of o.items||[]){if(!Number.isSafeInteger(item.qty)||item.qty<1)fail(400,'Số lượng nhập kho chưa hợp lệ.');needs[item.product.id]=(needs[item.product.id]||0)+item.qty}for(const id of Object.keys(needs))if(!await row(db,'SELECT id FROM products WHERE id=?',id))fail(409,'Sản phẩm đã bị xóa, không thể tự nhập lại kho. Bỏ chọn nhập kho và xử lý thủ công.');const nextBody=JSON.stringify(o);const changes=[sql(db,'UPDATE orders SET body=?,status=? WHERE id=? AND body=?',nextBody,o.status,id,found.body),...Object.entries(needs).map(([pid,qty])=>sql(db,'UPDATE products SET stock=stock+?,revision=revision+1 WHERE id=? AND EXISTS(SELECT 1 FROM orders WHERE id=? AND body=?)',qty,pid,id,nextBody))];const result=await db.batch(changes);if(!result[0].meta.changes)fail(409,'Đơn đã thay đổi. Tải lại trước khi lưu.');return o}
export async function salesAnalytics(db,params){const range=period(params),args=[range.start,range.end],where='o.created_at>=? AND o.created_at<?';const kpis=await row(db,`SELECT COUNT(*) orders,COUNT(DISTINCT o.user_id) buyers,COUNT(DISTINCT CASE WHEN o.status=5 THEN o.user_id END) deliveredBuyers,COALESCE(SUM(o.status=5),0) delivered,COALESCE(SUM(o.status=6),0) cancelled,COALESCE(SUM(o.status=7),0) returnRequested,COALESCE(SUM(o.status=8),0) returned,COALESCE(SUM(CASE WHEN o.status BETWEEN 0 AND 4 THEN 1 ELSE 0 END),0) processing,COALESCE(SUM(CASE WHEN o.status=5 THEN ${NET} ELSE 0 END),0) deliveredRevenue,COALESCE(SUM(CASE WHEN o.status NOT IN(6,8) THEN ${NET} ELSE 0 END),0) activeValue FROM orders o WHERE ${where}`,...args);
const buyers=await row(db,`SELECT COUNT(*) repeatBuyers FROM (SELECT user_id FROM orders o WHERE ${where} GROUP BY user_id HAVING COUNT(*)>1)`,...args);Object.assign(kpis,buyers);kpis.cancelRate=kpis.orders?kpis.cancelled/kpis.orders*100:0;kpis.returnRate=kpis.orders?kpis.returned/kpis.orders*100:0;kpis.averageDelivered=kpis.delivered?Math.round(kpis.deliveredRevenue/kpis.delivered):0;
const daily=await rows(db,`SELECT strftime('%Y-%m-%d',o.created_at/1000,'unixepoch','+7 hours') day,COUNT(*) orders,SUM(o.status=6) cancelled,SUM(o.status=8) returned,SUM(CASE WHEN o.status=5 THEN ${NET} ELSE 0 END) revenue FROM orders o WHERE ${where} GROUP BY day ORDER BY day`,...args);
const hourly=await rows(db,`SELECT CAST(strftime('%H',o.created_at/1000,'unixepoch','+7 hours') AS INTEGER) hour,COUNT(*) orders FROM orders o WHERE ${where} GROUP BY hour ORDER BY hour`,...args);
const heatmap=await rows(db,`SELECT CAST(strftime('%w',o.created_at/1000,'unixepoch','+7 hours') AS INTEGER) weekday,CAST(strftime('%H',o.created_at/1000,'unixepoch','+7 hours') AS INTEGER) hour,COUNT(*) orders FROM orders o WHERE ${where} GROUP BY weekday,hour`,...args);
const statuses=await rows(db,`SELECT o.status,COUNT(*) orders FROM orders o WHERE ${where} GROUP BY o.status`,...args);
const products=await rows(db,`SELECT json_extract(i.value,'$.product.id') id,MAX(json_extract(i.value,'$.product.name')) name,SUM(json_extract(i.value,'$.qty')) quantity,COUNT(DISTINCT o.id) orders,SUM(json_extract(i.value,'$.qty')*json_extract(i.value,'$.unit')) gross FROM orders o,json_each(o.body,'$.items') i WHERE ${where} AND o.status=5 GROUP BY json_extract(i.value,'$.product.id') ORDER BY quantity DESC,gross DESC LIMIT 10`,...args);
const customers=await rows(db,`SELECT o.user_id id,MAX(json_extract(o.body,'$.shipping.fullName')) name,MAX(json_extract(o.body,'$.owner')) email,COUNT(*) orders,SUM(o.status=5) delivered,SUM(CASE WHEN o.status=5 THEN ${NET} ELSE 0 END) revenue,MIN(o.created_at) firstOrder,MAX(o.created_at) lastOrder FROM orders o WHERE ${where} GROUP BY o.user_id ORDER BY lastOrder DESC LIMIT 30`,...args);
const reasons=await rows(db,`SELECT o.status,COALESCE(NULLIF(CASE WHEN o.status=6 THEN json_extract(o.body,'$.cancelReason') ELSE json_extract(o.body,'$.returnReason') END,''),'Chưa có lý do') reason,COUNT(*) orders FROM orders o WHERE ${where} AND o.status IN(6,7,8) GROUP BY o.status,reason ORDER BY orders DESC LIMIT 15`,...args);
return{range:{from:range.from,to:range.to,timezone:'Asia/Ho_Chi_Minh'},kpis,daily,hourly,heatmap,statuses,products,customers,reasons,generatedAt:new Date().toISOString(),definitions:{cohort:'Tất cả chỉ số lọc theo ngày tạo đơn; trạng thái là trạng thái hiện tại.',revenue:'Giá trị hàng của đơn hiện Đã giao, trừ giảm giá, không gồm phí vận chuyển. Không phải tiền thực thu hoặc lợi nhuận.',products:'Số lượng trong đơn hiện Đã giao; doanh số sản phẩm trước giảm giá toàn đơn.',buyers:'Khách theo tài khoản đặt hàng. Khách lặp lại có ít nhất hai đơn trong khoảng đã chọn.'}}}
export async function handleAdminSales(req,env,user){const url=new URL(req.url),path=url.pathname;if(!path.startsWith('/api/admin/'))return null;if(!['/api/admin/analytics','/api/admin/orders'].includes(path)&&!path.startsWith('/api/admin/orders/'))return null;if(user?.role!=='admin')fail(403,'Bạn không có quyền quản trị.');if(path==='/api/admin/analytics'&&req.method==='GET')return response(await salesAnalytics(env.DB,url.searchParams));if(path==='/api/admin/orders'&&req.method==='GET'){const range=period(url.searchParams,false),q=clean(url.searchParams.get('q'),100),st=url.searchParams.get('status');let where='created_at>=? AND created_at<?',args=[range.start,range.end];if(st!==null&&st!==''){const n=Number(st);if(!Number.isInteger(n)||n<0||n>8)fail(400,'Trạng thái chưa hợp lệ.');where+=' AND status=?';args.push(n)}if(q){where+=" AND (instr(lower(id),lower(?))>0 OR instr(lower(COALESCE(json_extract(body,'$.owner'),'')),lower(?))>0 OR instr(lower(COALESCE(json_extract(body,'$.shipping.fullName'),'')),lower(?))>0 OR instr(COALESCE(json_extract(body,'$.shipping.phone'),''),?)>0)";args.push(q,q,q,q)}const count=await row(env.DB,'SELECT COUNT(*) total FROM orders WHERE '+where,...args);const requested=Number(url.searchParams.get('page')||1);if(!Number.isInteger(requested)||requested<1)fail(400,'Trang chưa hợp lệ.');const pages=Math.max(1,Math.ceil(count.total/20)),page=Math.min(requested,pages);const items=await rows(env.DB,'SELECT body FROM orders WHERE '+where+' ORDER BY created_at DESC,id DESC LIMIT 20 OFFSET ?',...args,(page-1)*20);return response({orders:items.map(r=>JSON.parse(r.body)),total:count.total,page,pages})}if(path.startsWith('/api/admin/orders/')&&req.method==='PUT'){const raw=await req.text();if(raw.length>20000)fail(413,'Nội dung quá dài.');let p;try{p=JSON.parse(raw)}catch{fail(400,'Nội dung không hợp lệ.')}if(!p||typeof p!=='object'||Array.isArray(p))fail(400,'Nội dung không hợp lệ.');return response(await updateSalesOrder(env.DB,path.split('/').at(-1),p,user))}return null}
