import {html,builtAssets,seedCatalog} from './generated.mjs';
const encoder=new TextEncoder(),ADMIN_ID='site-owner',COOKIE='__Host-imprint_session';
class HttpError extends Error{constructor(status,message){super(message);this.status=status}}
const fail=(status,message)=>{throw new HttpError(status,message)};
const json=(body,status=200,extra={})=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...extra}});
const stmt=(db,sql,...args)=>db.prepare(sql).bind(...args);
const all=async(db,sql,...args)=>(await stmt(db,sql,...args).all()).results;
const one=(db,sql,...args)=>stmt(db,sql,...args).first();
const hex=b=>Array.from(new Uint8Array(b),v=>v.toString(16).padStart(2,'0')).join('');
const random=()=>hex(crypto.getRandomValues(new Uint8Array(32)));
const digest=async v=>hex(await crypto.subtle.digest('SHA-256',encoder.encode(v)));
async function passwordHash(password,salt){const key=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveBits']);return hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt:encoder.encode(salt),iterations:100000,hash:'SHA-256'},key,256))}
function equal(a,b){if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0}
const text=(v,max=100)=>typeof v==='string'?v.trim().slice(0,max):'';
function integer(v,min,max){if(!Number.isSafeInteger(v)||v<min||v>max)fail(400,'Số liệu chưa hợp lệ.');return v}
function safeMedia(v,privateAllowed=false){return typeof v==='string'&&(/^\/static\/[a-f0-9]+\.[a-z0-9]+$/.test(v)||/^\/api\/files\/[a-f0-9-]+$/.test(v)||(privateAllowed&&/^\/api\/files\/[a-f0-9-]+\?preview=1$/.test(v)))}
async function body(req,max=2*1024*1024){if(Number(req.headers.get('content-length')||0)>max)fail(413,'Nội dung vượt dung lượng cho phép.');const raw=await req.text();if(encoder.encode(raw).length>max)fail(413,'Nội dung vượt dung lượng cho phép.');try{return JSON.parse(raw)}catch{fail(400,'Nội dung gửi lên chưa hợp lệ.')}}
function requireUser(u){if(!u)fail(401,'Vui lòng đăng nhập.');return u}
function requireAdmin(u){if(u?.role!=='admin')fail(403,'Bạn không có quyền quản trị.');return u}
function profile(row){const p=JSON.parse(row.profile||'{}');return{id:row.id,email:row.email,name:row.name,role:'customer',...p}}
async function identity(req,env){const siteEmail=req.headers.get('oai-authenticated-user-email');if(siteEmail&&env.ADMIN_EMAIL&&siteEmail.toLowerCase()===env.ADMIN_EMAIL.toLowerCase())return{id:ADMIN_ID,email:siteEmail,name:'Quản trị',role:'admin'};const token=req.headers.get('cookie')?.split(';').map(v=>v.trim()).find(v=>v.startsWith(COOKIE+'='))?.slice(COOKIE.length+1);if(!token)return null;const row=await one(env.DB,'SELECT u.* FROM sessions s JOIN users u ON s.user_id=u.id WHERE s.hash=? AND s.expires_at>?',await digest(token),Date.now());return row?profile(row):null}
function cookie(token,maxAge){return`${COOKIE}=${token}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`}
async function session(db,u){const token=random();await stmt(db,'INSERT INTO sessions(hash,user_id,expires_at) VALUES(?,?,?)',await digest(token),u.id,Date.now()+7*86400000).run();return cookie(token,7*86400)}
async function limit(db,key,max){const now=Date.now(),slot=Math.floor(now/900000),k=key+':'+slot;await stmt(db,'INSERT INTO throttle(key,attempts,expires_at) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET attempts=attempts+1',k,now+1800000).run();const row=await one(db,'SELECT attempts FROM throttle WHERE key=?',k);if(row.attempts>max)fail(429,'Bạn thao tác quá nhiều lần. Hãy thử lại sau 15 phút.');if(Math.random()<.02)await stmt(db,'DELETE FROM throttle WHERE expires_at<?',now).run()}
async function ensureCatalog(db){const rows=await all(db,'SELECT id FROM products LIMIT 1');const initialized=await one(db,'SELECT key FROM settings WHERE key=?','initialized');if(initialized)return;const statements=seedCatalog.products.map(p=>stmt(db,'INSERT OR IGNORE INTO products(id,body,stock) VALUES(?,?,?)',p.id,JSON.stringify(p),p.stock));for(const [key,val]of Object.entries({campaign:seedCatalog.campaign,coupons:seedCatalog.coupons,feedback:[],collections:seedCatalog.collections,initialized:true}))statements.push(stmt(db,'INSERT OR IGNORE INTO settings(key,body) VALUES(?,?)',key,JSON.stringify(val)));await db.batch(statements)}
async function catalog(db){const ps=await all(db,'SELECT * FROM products');const ss=await all(db,'SELECT * FROM settings');const out={products:ps.map(r=>({...JSON.parse(r.body),stock:r.stock,_revision:r.revision})),revisions:{}};for(const r of ss){if(r.key==='initialized')continue;out[r.key]=JSON.parse(r.body);out.revisions[r.key]=r.revision}return out}
async function assetOwned(db,id,u,publicRequired=false){const a=await one(db,'SELECT * FROM assets WHERE id=?',id);if(!a||publicRequired&&!a.public||!a.public&&a.owner!==u?.id&&u?.role!=='admin')fail(403,'Bạn không có quyền sử dụng ảnh này.');return a}
function mediaId(src){return src?.match(/^\/api\/files\/([a-f0-9-]+)/)?.[1]}
async function checkMedia(db,src,u,pub){if(!safeMedia(src))fail(400,'Nguồn ảnh hoặc video chưa hợp lệ.');const id=mediaId(src);if(id)await assetOwned(db,id,u,pub)}
async function normalizeDesign(db,d,u){if(!d||typeof d!=='object'||!Array.isArray(d.layers)||d.layers.length>100)fail(400,'Thiết kế chưa hợp lệ.');if(JSON.stringify(d).length>500000)fail(413,'Thiết kế quá lớn.');for(const l of d.layers){if(l.asset)await assetOwned(db,l.asset,u);if(l.type==='text'&&typeof l.text==='string'&&l.text.length>5000)fail(400,'Nội dung chữ quá dài.')}return d}
async function normalizeItems(db,items,u){if(!Array.isArray(items)||items.length>50)fail(400,'Giỏ hàng chưa hợp lệ.');const out=[];for(const i of items){const row=await one(db,'SELECT * FROM products WHERE id=?',i.product?.id||i.productId);if(!row)fail(409,'Sản phẩm không còn trong danh mục.');const p={...JSON.parse(row.body),stock:row.stock,_revision:row.revision},qty=integer(i.qty,1,99),size=i.size,color=i.color;if(!p.sizes.includes(size)||!p.colors.includes(color))fail(400,'Màu hoặc size không hợp lệ.');const sleeve=i.design?.sleeveColor||i.sleeveColor;if(p.garmentType==='raglan'&&!p.sleeveColors.includes(sleeve))fail(400,'Màu tay áo chưa hợp lệ.');const model=i.design?.model||i.model||'f';if(!['f','m'].includes(model)||p.garmentType==='baby'&&model!=='f')fail(400,'Mẫu mặc chưa hợp lệ.');const d=i.design?await normalizeDesign(db,i.design,u):null;if(d&&(d.productId!==p.id||d.color!==color||d.size!==size||!p.custom))fail(400,'Thiết kế chưa khớp sản phẩm.');if(d&&!i.rightsAt)fail(400,'Cần xác nhận quyền sử dụng thiết kế.');if(!safeMedia(i.preview,true))fail(400,'Ảnh xem trước chưa được lưu.');await assetOwned(db,mediaId(i.preview),u);out.push({id:text(i.id,80)||crypto.randomUUID(),product:p,qty,size,color,sleeveColor:sleeve||null,model,unit:Math.round(p.price*(1-(p.sale||0)/100)),design:d,preview:i.preview,rightsAt:d?new Date().toISOString():null,quality:Array.isArray(i.quality)?i.quality.slice(0,30).map(v=>text(v,200)):[]})}return out}
async function personal(db,u){if(!u||u.role==='admin')return{cart:[],cartRevision:0,designs:[],orders:[]};const c=await one(db,'SELECT * FROM carts WHERE user_id=?',u.id),ds=await all(db,'SELECT * FROM designs WHERE user_id=? ORDER BY updated_at DESC',u.id),os=await all(db,'SELECT * FROM orders WHERE user_id=? ORDER BY created_at DESC',u.id);return{cart:c?JSON.parse(c.body):[],cartRevision:c?.revision||0,designs:ds.map(d=>({id:d.id,owner:u.email,design:JSON.parse(d.body)})),orders:os.map(o=>JSON.parse(o.body))}}
function productValid(p){if(!p||typeof p!=='object')fail(400,'Sản phẩm chưa hợp lệ.');if(!/^[\w-]{1,80}$/.test(p.id)||!text(p.name,80)||!text(p.description,5000))fail(400,'Nhập tên và mô tả sản phẩm.');integer(p.price,1000,100000000);integer(p.stock,0,1000000);integer(p.sale||0,0,90);if(!['tee','tank','baby','sweater','longsleeve','hoodie','raglan'].includes(p.garmentType))fail(400,'Kiểu áo chưa hợp lệ.');for(const key of ['sizes','colors'])if(!Array.isArray(p[key])||!p[key].length||p[key].length>30||p[key].some(v=>!text(v,40)))fail(400,'Màu và size chưa hợp lệ.');if(p.garmentType==='raglan'&&(!Array.isArray(p.sleeveColors)||!p.sleeveColors.length))fail(400,'Thiếu màu tay áo.');p.models=p.garmentType==='baby'?['f']:['f','m'];delete p._revision;return p}
async function writeSetting(db,key,value,revision){integer(revision,1,1000000000);const result=await stmt(db,'UPDATE settings SET body=?,revision=revision+1 WHERE key=? AND revision=?',JSON.stringify(value),key,revision).run();if(result.meta.changes!==1)fail(409,'Nội dung đã được cập nhật ở nơi khác. Tải lại trang trước khi sửa.');return revision+1}
function shippingValid(v){const s=Object.fromEntries(['fullName','phone','city','ward','address','note'].map(k=>[k,text(v?.[k],k==='note'?500:200)]));if(!s.fullName||!/^0\d{9}$/.test(s.phone)||!s.city||!s.ward||s.address.length<5)fail(400,'Kiểm tra lại thông tin nhận hàng.');return s}
async function createOrder(db,u,payload){if(u.role==='admin')fail(400,'Dùng tài khoản khách để đặt hàng.');const key=text(payload.requestKey,100);if(!/^[\w-]{8,100}$/.test(key))fail(400,'Mã gửi đơn chưa hợp lệ.');const duplicate=await one(db,'SELECT body FROM orders WHERE user_id=? AND request_key=?',u.id,key);if(duplicate)return JSON.parse(duplicate.body);const cart=await one(db,'SELECT * FROM carts WHERE user_id=?',u.id);if(!cart)fail(400,'Giỏ hàng đang trống.');if(cart.revision!==payload.cartRevision)fail(409,'Giỏ hàng đã thay đổi. Tải lại giỏ trước khi đặt.');const items=await normalizeItems(db,JSON.parse(cart.body),u);if(!items.length)fail(400,'Giỏ hàng đang trống.');const shipping=shippingValid(payload.shipping),sub=items.reduce((sum,i)=>sum+i.unit*i.qty,0),ship=sub>=500000?0:30000;const codes=JSON.parse((await one(db,'SELECT body FROM settings WHERE key=?','coupons')).body);let discount=0;if(payload.coupon){const c=codes.find(c=>c.code===text(payload.coupon,24).toUpperCase()&&c.expiry>=new Date().toISOString().slice(0,10)&&sub>=c.min);if(!c)fail(400,'Mã giảm giá không hợp lệ hoặc đã hết hạn.');discount=Math.round(Math.min(sub,c.type==='percent'?sub*c.amount/100:c.amount,c.max||Infinity))}const now=Date.now(),o={id:'IP-'+crypto.randomUUID().slice(0,8).toUpperCase(),owner:u.email,date:new Date(now).toISOString(),shipping,items,sub,ship,discount,total:sub+ship-discount,status:0,payment:'Chưa thanh toán · Thanh toán khi nhận hàng',tracking:'',history:[{status:0,at:new Date(now).toISOString()}]};const needs={};for(const i of items)needs[i.product.id]=(needs[i.product.id]||0)+i.qty;
// D1 batch is transactional; CHECK(stock>=0) rolls back the entire order on concurrent overselling.
const statements=[stmt(db,'INSERT INTO orders(id,user_id,request_key,body,status,created_at) SELECT ?,?,?,?,0,? WHERE EXISTS(SELECT 1 FROM carts WHERE user_id=? AND revision=?)',o.id,u.id,key,JSON.stringify(o),now,u.id,payload.cartRevision),...Object.entries(needs).map(([id,q])=>stmt(db,'UPDATE products SET stock=stock-?,revision=revision+1 WHERE id=? AND EXISTS(SELECT 1 FROM orders WHERE id=?)',q,id,o.id)),stmt(db,'UPDATE carts SET body=?,revision=revision+1 WHERE user_id=? AND revision=? AND EXISTS(SELECT 1 FROM orders WHERE id=?)','[]',u.id,payload.cartRevision,o.id)];try{const results=await db.batch(statements);if(!results[0].meta.changes)fail(409,'Giỏ hàng đã thay đổi. Tải lại trước khi đặt.')}catch(e){const prior=await one(db,'SELECT body FROM orders WHERE user_id=? AND request_key=?',u.id,key);if(prior)return JSON.parse(prior.body);if(String(e).includes('stock_nonnegative')||String(e).includes('CHECK'))fail(409,'Một sản phẩm không đủ tồn kho. Kiểm tra giỏ hàng.');throw e}return o}
export async function handle(req,env){const url=new URL(req.url),path=url.pathname,db=env.DB;if(path.startsWith('/static/')){const a=builtAssets[path];if(!a)return new Response('Not found',{status:404});const bytes=Uint8Array.from(atob(a.base64),c=>c.charCodeAt(0));const headers={'Content-Type':a.type,'Cache-Control':'public,max-age=31536000,immutable','X-Content-Type-Options':'nosniff','Accept-Ranges':'bytes'};const range=req.headers.get('range')?.match(/^bytes=(\d+)-(\d*)$/);if(range){const start=+range[1],end=Math.min(range[2]?+range[2]:bytes.length-1,bytes.length-1);if(start>end)return new Response(null,{status:416});headers['Content-Range']=`bytes ${start}-${end}/${bytes.length}`;return new Response(bytes.slice(start,end+1),{status:206,headers})}return new Response(req.method==='HEAD'?null:bytes,{headers})}
if(!path.startsWith('/api/')){if(path!=='/'&&path!=='/index.html')return new Response('Not found',{status:404});return new Response(html,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-cache','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin'}})}
if(!db||!env.BUCKET)fail(503,'Dịch vụ lưu trữ chưa sẵn sàng.');if(!['GET','HEAD'].includes(req.method)){const origin=req.headers.get('origin');if(origin!==url.origin||req.headers.get('sec-fetch-site')==='cross-site')fail(403,'Nguồn yêu cầu chưa hợp lệ.');if(!path.startsWith('/api/upload')&&!req.headers.get('content-type')?.includes('application/json'))fail(415,'Định dạng yêu cầu chưa hợp lệ.')}
if(path==='/api/health')return json({ok:true,database:!!db,files:!!env.BUCKET});await ensureCatalog(db);let u=await identity(req,env);
if(path==='/api/bootstrap'&&req.method==='GET'){const result={...await catalog(db),user:u,...await personal(db,u)};if(u?.role==='admin')result.orders=(await all(db,'SELECT body FROM orders ORDER BY created_at DESC LIMIT 1000')).map(x=>JSON.parse(x.body));return json(result)}
if(path==='/api/auth/register'&&req.method==='POST'){const p=await body(req,10000),email=text(p.email,254).toLowerCase(),name=text(p.name,80),password=p.password;if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!name||typeof password!=='string'||password.length<8||password.length>128)fail(400,'Nhập họ tên, email và mật khẩu từ 8 đến 128 ký tự.');await limit(db,'register:'+req.headers.get('cf-connecting-ip'),8);if(env.ADMIN_EMAIL?.toLowerCase()===email)fail(400,'Email này dùng cho quản trị.');const salt=random(),id=crypto.randomUUID(),hash=await passwordHash(password,salt);try{await stmt(db,'INSERT INTO users(id,email,name,salt,password_hash,created_at) VALUES(?,?,?,?,?,?)',id,email,name,salt,hash,Date.now()).run()}catch(e){if(String(e).includes('UNIQUE'))fail(409,'Email này đã được sử dụng.');throw e}return json({user:{id,email,name,role:'customer'}},201,{'Set-Cookie':await session(db,{id})})}
if(path==='/api/auth/login'&&req.method==='POST'){const p=await body(req,10000),email=text(p.email,254).toLowerCase();if(typeof p.password!=='string'||p.password.length>128)fail(400,'Mật khẩu chưa hợp lệ.');await limit(db,'login:'+await digest(email)+':'+req.headers.get('cf-connecting-ip'),12);const row=await one(db,'SELECT * FROM users WHERE email=?',email),hash=await passwordHash(p.password,row?.salt||'unregistered-user');if(!row||!equal(hash,row.password_hash))fail(401,'Email hoặc mật khẩu chưa đúng.');return json({user:profile(row)},200,{'Set-Cookie':await session(db,row)})}
if(path==='/api/auth/logout'&&req.method==='POST'){const token=req.headers.get('cookie')?.split(';').map(v=>v.trim()).find(v=>v.startsWith(COOKIE+'='))?.slice(COOKIE.length+1);if(token)await stmt(db,'DELETE FROM sessions WHERE hash=?',await digest(token)).run();return json({ok:true},200,{'Set-Cookie':cookie('',0)})}
if(path==='/api/profile'&&req.method==='PUT'){requireUser(u);if(u.role==='admin')fail(400,'Hồ sơ quản trị được quản lý bằng tài khoản ChatGPT.');const p=await body(req,10000),name=text(p.name,80),profileData={phone:text(p.phone,20),address:text(p.address,200)};if(!name)fail(400,'Nhập họ tên.');await stmt(db,'UPDATE users SET name=?,profile=? WHERE id=?',name,JSON.stringify(profileData),u.id).run();return json({user:{...u,name,...profileData}})}
if(path==='/api/cart'&&req.method==='PUT'){requireUser(u);if(u.role==='admin')fail(403,'Quản trị không sử dụng giỏ khách.');const p=await body(req),items=await normalizeItems(db,p.items,u),existing=await one(db,'SELECT revision FROM carts WHERE user_id=?',u.id);if((existing?.revision||0)!==p.revision)fail(409,'Giỏ đã thay đổi trên thiết bị khác. Tải lại trang.');if(!existing){try{await stmt(db,'INSERT INTO carts(user_id,body,revision) VALUES(?,?,1)',u.id,JSON.stringify(items)).run()}catch(e){fail(409,'Giỏ đã thay đổi. Tải lại trang.')}return json({items,revision:1})}const r=await stmt(db,'UPDATE carts SET body=?,revision=revision+1 WHERE user_id=? AND revision=?',JSON.stringify(items),u.id,p.revision).run();if(!r.meta.changes)fail(409,'Giỏ đã thay đổi. Tải lại trang.');return json({items,revision:p.revision+1})}
if(path==='/api/designs'&&req.method==='POST'){requireUser(u);const p=await body(req),id=text(p.id,80);if(!/^[\w-]{1,80}$/.test(id))fail(400,'Mã thiết kế chưa hợp lệ.');const old=await one(db,'SELECT user_id FROM designs WHERE id=?',id);if(old&&old.user_id!==u.id)fail(403,'Không thể sửa thiết kế này.');const d=await normalizeDesign(db,p.design,u);await stmt(db,'INSERT INTO designs(id,user_id,body,updated_at) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET body=excluded.body,updated_at=excluded.updated_at',id,u.id,JSON.stringify(d),Date.now()).run();return json({id,owner:u.email,design:d})}
if(path.startsWith('/api/designs/')&&req.method==='DELETE'){requireUser(u);await stmt(db,'DELETE FROM designs WHERE id=? AND user_id=?',path.split('/').at(-1),u.id).run();return json({ok:true})}
if(path==='/api/orders'&&req.method==='POST'){requireUser(u);await limit(db,'order:'+u.id,30);return json(await createOrder(db,u,await body(req,20000)),201)}
if(path==='/api/upload'&&req.method==='POST'){requireUser(u);await limit(db,'upload:'+u.id,180);const publicFile=url.searchParams.get('public')==='1';if(publicFile)requireAdmin(u);const type=req.headers.get('content-type')?.split(';')[0];const allowed=['image/jpeg','image/png','image/webp','image/avif','video/mp4','video/webm'];if(!allowed.includes(type)||type.startsWith('video/')&&!publicFile)fail(415,'Định dạng tệp chưa được hỗ trợ.');const max=type.startsWith('video/')?80*1024*1024:50*1024*1024,size=Number(req.headers.get('content-length'));if(!size||size>max)fail(413,'Tệp vượt dung lượng cho phép.');const usage=await one(db,'SELECT COALESCE(SUM(size),0) AS size FROM assets WHERE owner=?',u.id);if(u.role!=='admin'&&usage.size+size>1024*1024*1024)fail(413,'Tài khoản đạt giới hạn 1 GB ảnh.');const id=crypto.randomUUID(),key='uploads/'+id,meta={name:text(url.searchParams.get('name'),150),width:Number(url.searchParams.get('width'))||0,height:Number(url.searchParams.get('height'))||0};await env.BUCKET.put(key,req.body,{httpMetadata:{contentType:type}});try{await stmt(db,'INSERT INTO assets(id,owner,object_key,type,size,public,metadata,created_at) VALUES(?,?,?,?,?,?,?,?)',id,u.id,key,type,size,+publicFile,JSON.stringify(meta),Date.now()).run()}catch(e){await env.BUCKET.delete(key);throw e}return json({id,url:'/api/files/'+id,...meta},201)}
if(path.startsWith('/api/files/')&&req.method==='GET'){const id=path.split('/').at(-1),a=await assetOwned(db,id,u);const range=req.headers.get('range');const obj=await env.BUCKET.get(a.object_key,range?{range:req.headers}:undefined);if(!obj)fail(404,'Tệp không còn tồn tại.');const h=new Headers({'Content-Type':a.type,'Cache-Control':a.public?'public,max-age=3600':'private,no-store','X-Content-Type-Options':'nosniff','Accept-Ranges':'bytes'});if(obj.range){h.set('Content-Range',`bytes ${obj.range.offset}-${obj.range.offset+obj.range.length-1}/${obj.size}`)}return new Response(obj.body,{status:obj.range?206:200,headers:h})}
if(path.startsWith('/api/admin/')){requireAdmin(u);if(path==='/api/admin/products'&&req.method==='POST'){const p=productValid(await body(req,100000)),old=await one(db,'SELECT id FROM products WHERE id=?',p.id);if(old)fail(409,'Mã sản phẩm đã tồn tại.');await checkMedia(db,p.img,u,true);await stmt(db,'INSERT INTO products(id,body,stock) VALUES(?,?,?)',p.id,JSON.stringify(p),p.stock).run();return json({...p,_revision:1},201)}
if(path.startsWith('/api/admin/products/')){const id=path.split('/').at(-1);if(req.method==='DELETE'){await stmt(db,'DELETE FROM products WHERE id=?',id).run();return json({ok:true})}if(req.method==='PUT'){const payload=await body(req,100000),rev=payload._revision,p=productValid(payload);if(p.id!==id)fail(400,'Mã sản phẩm chưa hợp lệ.');await checkMedia(db,p.img,u,true);const r=await stmt(db,'UPDATE products SET body=?,stock=?,revision=revision+1 WHERE id=? AND revision=?',JSON.stringify(p),p.stock,id,rev).run();if(!r.meta.changes)fail(409,'Sản phẩm đã thay đổi. Tải lại trang trước khi sửa.');return json({...p,_revision:rev+1})}}
if(path.startsWith('/api/admin/settings/')&&req.method==='PUT'){const key=path.split('/').at(-1),p=await body(req),v=p.value;if(key==='campaign'){if(!text(v,120)||v.length>120)fail(400,'Thông báo dài tối đa 120 ký tự.')}else if(key==='coupons'){if(!Array.isArray(v)||v.length>100)fail(400,'Danh sách mã giảm chưa hợp lệ.');for(const c of v){if(!/^[A-Z0-9_-]{3,24}$/.test(c.code)||!['percent','fixed'].includes(c.type)||!/^\d{4}-\d{2}-\d{2}$/.test(c.expiry))fail(400,'Mã giảm giá chưa hợp lệ.');integer(c.amount,1,c.type==='percent'?100:100000000);integer(c.min,0,100000000);integer(c.max,1,100000000)}}else if(key==='feedback'){if(!Array.isArray(v)||v.length>200)fail(400,'Danh sách ảnh quá dài.');for(const f of v){if(!f.consentAt||!text(f.caption,200)||!text(f.name,80))fail(400,'Nhập tên, chú thích và xác nhận đồng ý.');await checkMedia(db,f.img,u,true)}}else if(key==='collections'){if(!Array.isArray(v)||v.length>100)fail(400,'Danh sách bộ sưu tập quá dài.');for(const c of v){if(!text(c.title,100)||!['image','video','youtube'].includes(c.kind))fail(400,'Bộ sưu tập chưa hợp lệ.');if(c.kind==='youtube'){if(!/^[\w-]{11}$/.test(c.src))fail(400,'Video YouTube chưa hợp lệ.')}else await checkMedia(db,c.src,u,true)}}else fail(404,'Không tìm thấy nội dung.');return json({revision:await writeSetting(db,key,v,p.revision)})}
if(path.startsWith('/api/admin/orders/')&&req.method==='PUT'){const id=path.split('/').at(-1),p=await body(req,20000),row=await one(db,'SELECT * FROM orders WHERE id=?',id);if(!row)fail(404,'Không tìm thấy đơn hàng.');const o=JSON.parse(row.body);integer(p.status,0,5);if(p.status!==o.status){o.status=p.status;o.history.push({status:p.status,at:new Date().toISOString()})}o.tracking=text(p.tracking,100);await stmt(db,'UPDATE orders SET body=?,status=? WHERE id=?',JSON.stringify(o),o.status,id).run();return json(o)}}
fail(404,'Không tìm thấy chức năng.');}
export default {async fetch(req,env,ctx){try{return await handle(req,env)}catch(e){if(!e.status)console.error('ImPrint API error',e);return json({error:e.status?e.message:'Dịch vụ tạm thời không xử lý được yêu cầu. Vui lòng thử lại.'},e.status||503)}}};
