let backendReady=false,serverSnapshot=null,cartRevision=0,syncQueue=Promise.resolve(),uploadedAssets=new Map(),uploadedMedia=new Map();
async function api(path,method='GET',value){const r=await fetch(path,{method,credentials:'same-origin',headers:value!==undefined?{'Content-Type':'application/json'}:{},body:value!==undefined?JSON.stringify(value):undefined});let result;try{result=await r.json()}catch{throw Error('Máy chủ chưa phản hồi đúng. Hãy tải lại trang.')}if(!r.ok){const e=Error(result.error||'Không thể xử lý yêu cầu.');e.status=r.status;throw e}return result}
function updateHeader(){$('#count').textContent=data.cart.reduce((s,i)=>s+i.qty,0);$('#announcement').textContent=data.campaign;$('#accountBtn').textContent=user?user.name:'Tài khoản'}
function rememberSnapshot(){serverSnapshot=JSON.parse(JSON.stringify({products:data.products,campaign:data.campaign,coupons:data.coupons,feedback:data.feedback,collections:collectionItems(),orders:data.orders,designs:data.designs,cart:data.cart}));}
async function refreshBackend({keepGuest=false}={}){const guest=keepGuest&&!user?data?.cart||[]:[];const result=await api('/api/bootstrap');user=result.user;cartRevision=result.cartRevision||0;data={...result,cart:result.user?result.cart:guest,users:[],catalogV5:true};rememberSnapshot();updateHeader();return result}
async function uploadBlob(blob,publicFile=false,meta={}){const q=new URLSearchParams({public:publicFile?'1':'0',name:meta.name||'ảnh',width:meta.width||0,height:meta.height||0});const r=await fetch('/api/upload?'+q,{method:'POST',credentials:'same-origin',headers:{'Content-Type':blob.type},body:blob});const result=await r.json();if(!r.ok)throw Error(result.error||'Không tải được tệp.');return result}
async function mediaRemote(src,publicFile=false){if(!src||!src.startsWith('data:'))return src;if(uploadedMedia.has(src))return uploadedMedia.get(src);const file=await(await fetch(src)).blob(),out=await uploadBlob(file,publicFile);uploadedMedia.set(src,out.url);return out.url}
async function designRemote(d){const out=clone(d);for(const layer of out.layers){if(!layer.asset)continue;let id=layer.asset;if(uploadedAssets.has(id)){layer.asset=uploadedAssets.get(id);continue}if(await get('assets',id)){const a=await get('assets',id);if(a.cloudId&&a.cloudOwner===user.id){layer.asset=a.cloudId;uploadedAssets.set(id,a.cloudId);continue}const r=await uploadBlob(a.original,false,{name:a.name,width:a.width,height:a.height});a.cloudId=r.id;a.cloudOwner=user.id;await put('assets',id,a);await put('assets',r.id,a);uploadedAssets.set(id,r.id);layer.asset=r.id}else{layer.asset=id}}return out}
async function itemsRemote(items){const out=[];for(const item of items){const next=clone(item);if(next.design)next.design=await designRemote(next.design);next.preview=await mediaRemote(next.preview,false);out.push(next)}return out}
const equalData=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
async function syncAdmin(){const before=serverSnapshot;for(let i=0;i<data.products.length;i++){let p=data.products[i],old=before.products.find(x=>x.id===p.id);if(!old||!equalData(p,old)){p=clone(p);p.img=await mediaRemote(p.img,true);const updated=await api('/api/admin/products'+(old?'/'+p.id:''),old?'PUT':'POST',p);data.products[i]=updated;const pos=before.products.findIndex(x=>x.id===p.id);if(pos>=0)before.products[pos]=clone(updated);else before.products.push(clone(updated))}}for(const old of before.products.slice())if(!data.products.some(p=>p.id===old.id)){await api('/api/admin/products/'+old.id,'DELETE',{});before.products=before.products.filter(p=>p.id!==old.id)}for(const key of ['campaign','coupons','feedback','collections']){const value=key==='collections'?collectionItems():data[key];if(equalData(value,before[key]))continue;let next=clone(value);if(key==='feedback')for(const f of next)f.img=await mediaRemote(f.img,true);if(key==='collections')for(const c of next)if(c.kind!=='youtube')c.src=await mediaRemote(c.src,true);const result=await api('/api/admin/settings/'+key,'PUT',{value:next,revision:data.revisions[key]});data[key]=next;data.revisions[key]=result.revision;before[key]=clone(next)}for(let i=0;i<data.orders.length;i++){const o=data.orders[i],old=before.orders.find(x=>x.id===o.id);if(old&&(old.status!==o.status||old.tracking!==o.tracking)){const saved=await api('/api/admin/orders/'+o.id,'PUT',{status:o.status,tracking:o.tracking});data.orders[i]=saved;before.orders[before.orders.findIndex(x=>x.id===o.id)]=clone(saved)}}}
async function syncCustomer(){if(!equalData(data.cart,serverSnapshot.cart)){const out=await api('/api/cart','PUT',{items:await itemsRemote(data.cart),revision:cartRevision});data.cart=out.items;cartRevision=out.revision;serverSnapshot.cart=clone(out.items)}for(let i=0;i<data.designs.length;i++){const d=data.designs[i],old=serverSnapshot.designs.find(x=>x.id===d.id);if(!old||!equalData(d,old)){const saved=await api('/api/designs','POST',{id:d.id,design:await designRemote(d.design)});data.designs[i]=saved;const pos=serverSnapshot.designs.findIndex(x=>x.id===d.id);if(pos>=0)serverSnapshot.designs[pos]=clone(saved);else serverSnapshot.designs.push(clone(saved))}}for(const old of serverSnapshot.designs.slice())if(!data.designs.some(d=>d.id===old.id)){await api('/api/designs/'+old.id,'DELETE',{});serverSnapshot.designs=serverSnapshot.designs.filter(d=>d.id!==old.id)}}
persist=function(){const job=async()=>{if(!backendReady)return true;try{if(user?.role==='admin')await syncAdmin();else if(user)await syncCustomer();else await put('state','guest-cart',data.cart);updateHeader();return true}catch(e){toast(e.message);throw e}};const task=syncQueue.then(job);syncQueue=task.catch(()=>{});return task};
const oldGetBackend=get;get=async function(store,key){const cached=await oldGetBackend(store,key);if(store!=='assets'||cached||!backendReady)return cached;if(!user)return null;const r=await fetch('/api/files/'+key,{credentials:'same-origin'});if(!r.ok)throw Error('Không tải được ảnh gốc. Hãy đăng nhập lại.');const original=await r.blob(),im=await createImageBitmap(original),scale=Math.min(1,1800/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);c.getContext('2d').drawImage(im,0,0,c.width,c.height);const a={original,preview:await new Promise(res=>c.toBlob(res,'image/png')),width:im.width,height:im.height,name:'Ảnh đã lưu',cloudId:key,cloudOwner:user.id};im.close();await put('assets',key,a);return a};
const authBeforeBackend=auth;auth=function(register=false,adminLogin=false){if(adminLogin){if($('#modal').open)$('#modal').close();go('admin');return}authBeforeBackend(register,false);const note=$('#modal .muted');if(note)note.textContent='Đăng nhập để lưu thiết kế, giỏ hàng và theo dõi đơn trên mọi thiết bị.'};
submitAuth=async function(register){const button=$('#authSubmit');button.disabled=true;try{const guest=user?[]:clone(data.cart),response=await api('/api/auth/'+(register?'register':'login'),'POST',{email:$('#email').value.trim(),password:$('#password').value,name:$('#authName')?.value.trim()});user=response.user;await refreshBackend();if(guest.length&&user.role!=='admin'){const ids=new Set(data.cart.map(i=>i.id));data.cart.push(...guest.filter(i=>!ids.has(i.id)));await persist()}await put('state','guest-cart',[]);$('#modal').close();const next=authNext;authNext=null;if(next)next();else go(user.role==='admin'?'admin':'account')}catch(e){$('#authError').textContent=e.message;button.disabled=false}};
logout=async function(){try{await api('/api/auth/logout','POST',{});const admin=user?.role==='admin';user=null;data.cart=[];data.designs=[];data.orders=[];uploadedAssets.clear();uploadedMedia.clear();for(const im of images.values())im.close?.();images.clear();await new Promise((res,rej)=>{const t=db.transaction('assets','readwrite');t.objectStore('assets').clear();t.oncomplete=res;t.onerror=()=>rej(t.error)});await put('state','guest-cart',[]);await refreshBackend();go('home')}catch(e){toast(e.message)}};
saveProfile=async function(){try{const r=await api('/api/profile','PUT',{name:$('#profileName').value.trim(),phone:$('#profilePhone').value,address:$('#profileAddress').value});user=r.user;updateHeader();toast('Đã lưu thông tin.')}catch(e){toast(e.message)}};
const checkoutBeforeBackend=checkout;checkout=function(){checkoutBeforeBackend();if(!$('#checkoutForm'))return;app.querySelector('.notice').textContent='Đơn hàng được gửi đến ImPrint. Cửa hàng sẽ kiểm tra thiết kế và liên hệ xác nhận trước khi sản xuất.';$('#placeBtn').textContent='Đặt hàng';const label=$('#checkoutForm input[name="pay"]').parentElement;label.lastChild.textContent=' Thanh toán khi nhận hàng';};
let orderRequestKey=null;placeOrder=async function(){if(busy||!user||!data.cart.length)return;busy=true;$('#placeBtn').disabled=true;try{await persist();orderRequestKey||=crypto.randomUUID();const shipping=Object.fromEntries(['fullName','phone','city','ward','address','note'].map(k=>[k,$('#'+k).value.trim()]));const order=await api('/api/orders','POST',{shipping,coupon,cartRevision,requestKey:orderRequestKey});orderRequestKey=null;coupon='';await refreshBackend();go('account');toast('Đã gửi đơn '+order.id+' đến ImPrint.')}catch(e){toast(e.message);if($('#placeBtn'))$('#placeBtn').disabled=false}finally{busy=false}};
const adminBeforeBackend=admin;admin=function(){if(user?.role==='admin'){adminBeforeBackend();const notice=app.querySelector('.notice');if(notice)notice.textContent='Nội dung được lưu trên máy chủ và hiển thị cho khách. Đơn hàng, ảnh gốc và thiết kế được lưu chung.';return}app.innerHTML=`<div class="wrap section admin-login-layout"><div><div class="eyebrow">IMPRINT · QUẢN TRỊ</div><h1>Quản lý cửa hàng.</h1><p>Đăng nhập bằng email và mật khẩu quản trị để quản lý cửa hàng.</p></div><div class="panel"><h2>Đăng nhập quản trị</h2><p>Chỉ tài khoản chủ website có quyền truy cập.</p><button class="button primary" onclick="auth(false)">Đăng nhập quản trị</button><p class="muted">Tài khoản quản trị do chủ cửa hàng thiết lập.</p></div></div>`};
const helpBeforeBackend=help;help=function(){helpBeforeBackend();app.querySelectorAll('details').forEach(d=>{const q=d.querySelector('summary').textContent;if(q==='Thanh toán và giao hàng')d.querySelector('p').textContent='Đặt hàng trên website để gửi thông tin và thiết kế đến ImPrint. Hiện hỗ trợ thanh toán khi nhận hàng; cửa hàng kiểm tra thiết kế và liên hệ xác nhận trước sản xuất. Thanh toán trực tuyến và hãng vận chuyển chưa được kết nối.';if(q==='Thông tin và dữ liệu được lưu ở đâu?')d.querySelector('p').textContent='Tài khoản, thiết kế đã lưu, giỏ hàng sau đăng nhập và đơn hàng được lưu trên máy chủ. Bản nháp trước đăng nhập nằm trên thiết bị hiện tại.'})};
init=async function(){app.innerHTML='<div class="wrap section"><p>Đang mở ImPrint…</p></div>';sessionStorage.removeItem('imprint-admin-session');db=await new Promise((res,rej)=>{const r=indexedDB.open('imprint_studio_v3',1);r.onupgradeneeded=()=>{r.result.createObjectStore('state');r.result.createObjectStore('assets')};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});const guest=await oldGetBackend('state','guest-cart')||[];await Promise.all([loadMocks(),...FONT_NAMES.map(f=>document.fonts.load('32px "'+f+'"'))]);data={cart:guest};await refreshBackend({keepGuest:true});backendReady=true;document.getElementById('adminNav')?.remove();installCompanion();document.querySelector('header nav').insertAdjacentHTML('beforeend','<a href="#home" onclick="event.preventDefault();openCollections()">Bộ sưu tập</a>');document.querySelector('footer .wrap').insertAdjacentHTML('beforeend',`<nav class="social-links" aria-label="Mạng xã hội">${SOCIALS}</nav>`);document.querySelector('#companionPanel nav').insertAdjacentHTML('beforeend',SOCIALS);if(new URL(location.href).searchParams.has('admin')){window.history.replaceState(null,'','/#admin')}route();};
